import 'package:flutter/material.dart';
const appname = "Shop App";
const appversion = "Version 1.0.0";
const credits = "@2023 ShopApp";
const email = "Email";
const emailHint = "admin@gmail.com";
const password = "Password";
const passwordHint = "12345";
const forgetPass = "Forget password";
const login = "login";
const pass = "password";
const createNewAccount = " or create new account";
const forgetPassword = "Forget Password";
